name: Gravity Forms - Upload Files

on:
  push:
    tags:
      - 'gravity-forms-upload-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    name: Upload files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v6

      - name: Extract version from tag
        id: vars
        run: |
          TAG=${GITHUB_REF##*/}
          VERSION=${TAG#gravity-forms-upload-v}
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Install SVN
        run: sudo apt-get install -y subversion

      - name: Checkout SVN
        run: |
          svn checkout --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --non-interactive --trust-server-cert https://plugins.svn.wordpress.org/chip-for-gravity-forms/ svn-tags

      - name: Check for version conflict
        run: |
          VERSION="${{ steps.vars.outputs.version }}"
          if [ -d "svn-tags/tags/$VERSION" ]; then
            echo "❌ The tag '$VERSION' already exists in SVN. Aborting."
            exit 1
          fi

      - name: Prepare plugin folder in tags
        run: |
          VERSION="${{ steps.vars.outputs.version }}"
          mkdir -p "svn-tags/tags/$VERSION"
          git archive HEAD | tar -x -C "svn-tags/tags/$VERSION"
          echo "✅ Prepared plugin folder for $VERSION"
          ls -la "svn-tags/tags/$VERSION/"

      - name: Track new version folder
        run: |
          VERSION="${{ steps.vars.outputs.version }}"
          cd svn-tags/tags
          svn add "$VERSION"

      - name: List file changes
        run: |
          cd svn-tags
          echo "SVN status:"
          svn status

      - name: Commit changes to SVN
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)

          cd svn-tags
          svn commit -m "$COMMIT_MSG" \
            --username "$SVN_USERNAME" \
            --password "$SVN_PASSWORD" \
            --non-interactive --trust-server-cert
